### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by kdenaeem** [b1sergiu/deezcord-plus#1]
How are you supposed to run this?
I downloaded the zip and extracted, I see a lot of .dlls
Am I supposed to inject them somewhere?
Thanks

**Comment by b1sergiu** [comment]
There's a `Deezcord.exe` file that you're supposed tor run. I've updated it to v1.1, you might want to check it out.

**Comment by kdenaeem** [comment]
> There's a `Deezcord.exe` file that you're supposed tor run. I've updated it to v1.1, you might want to check it out.

Hey, I got it showing the song. But How do I get this showing up on discord? I cant find it on game activity

**Comment by kdenaeem** [comment]
Actually, it works perfectly fine
Thanks a lot, great work.
How do you work on stuff like this? Id like to start developing applications like this.
I know some C++, where do you think I should start?

**Comment by b1sergiu** [comment]
I started learning C# by building Steam and Discord bots. I'd recommend the SoloLearn course on C++ to learn the basics, then just google tutorials.
